version: "3.8"

services:
  myappfrontend:
    image: shivangsharma28/cloudsage-frontend:v2
    ports:
      - "9500:80"
    container_name: myappfrontend
    restart: always
    depends_on:
      myappbackend:
        condition: service_started
    networks:
      - myappnetwork

  myappbackend:
    image: shivangsharma28/cloudsage-backend:v2
    ports:
      - "8000:8000"
    container_name: myappbackend
    restart: always
    depends_on:
      myappdb:
        condition: service_healthy
    networks:
      - myappnetwork

  myappdb:
    image: postgres:15
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    container_name: myappdb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myappuser -d myappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - myappdbdata:/var/lib/postgresql/data
    networks:
      - myappnetwork

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    ports:
      - "8081:8080"
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    networks:
      - myappnetwork
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - myappnetwork
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - myappnetwork
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

volumes:
  myappdbdata:
  prometheus_data:
  grafana_data:

networks:
  myappnetwork:
    driver: bridge